import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useSearchParams } from "react-router-dom";
import type { RootState } from "../store/store";
import { addBooking, updateBooking, type Booking } from "../features/booking/bookingSlice";

export function BookingsPage() {
  const dispatch = useDispatch();
  const { bookings, services } = useSelector((state: RootState) => state.booking);
  const [params] = useSearchParams();
  const [open, setOpen] = useState(params.get("new") === "1");
  const [query, setQuery] = useState("");
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    dispatch(addBooking({ customer: String(form.get("customer")), email: String(form.get("email")), service: String(form.get("service")), staff: String(form.get("staff")), date: String(form.get("date")), time: String(form.get("time")), status: form.get("status") as Booking["status"], payment: form.get("payment") as Booking["payment"], paymentMethod: form.get("paymentMethod") as Booking["paymentMethod"] }));
    setOpen(false);
  }
  const filtered = bookings.filter((row) => `${row.customer} ${row.service} ${row.staff}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h1 className="text-3xl font-semibold tracking-tight text-slate-900">Bookings</h1><button onClick={() => setOpen(true)} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800">+ New Booking</button></div>
    <div className="page-card overflow-hidden"><div className="border-b border-slate-200 p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search customer, service or staff" className="w-full max-w-md rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm" /></div><div className="table-shell"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{["Customer", "Service", "Staff", "Date & Time", "Status", "Payment"].map((heading) => <th key={heading} className="px-4 py-3 font-medium">{heading}</th>)}</tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-t border-slate-200"><td className="px-4 py-3 font-medium text-slate-900">{row.customer}<div className="text-xs font-normal text-slate-500">{row.email}</div></td><td className="px-4 py-3 text-slate-600">{row.service}</td><td className="px-4 py-3 text-slate-600">{row.staff}</td><td className="px-4 py-3 text-slate-600">{row.date} · {row.time}</td><td className="px-4 py-3"><select value={row.status} onChange={(event) => dispatch(updateBooking({ id: row.id, status: event.target.value as Booking["status"] }))} className="rounded-lg border border-slate-200 px-2 py-1 text-xs"><option>Pending</option><option>Confirmed</option><option>Completed</option></select></td><td className="px-4 py-3"><select value={row.payment} onChange={(event) => dispatch(updateBooking({ id: row.id, payment: event.target.value as Booking["payment"] }))} className="rounded-lg border border-slate-200 px-2 py-1 text-xs"><option>Unpaid</option><option>Deposit</option><option>Paid</option></select><div className="mt-1 text-xs text-slate-500">{row.paymentMethod}</div></td></tr>)}</tbody></table></div></div>
    {open && <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-semibold">New booking</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><input name="customer" required placeholder="Customer name" className="rounded-xl border border-slate-200 px-3 py-2.5" /><input name="email" type="email" required placeholder="Customer email" className="rounded-xl border border-slate-200 px-3 py-2.5" /><select name="service" className="rounded-xl border border-slate-200 px-3 py-2.5">{services.map((service) => <option key={service.id}>{service.name}</option>)}</select><input name="staff" required defaultValue="Maria" placeholder="Staff member" className="rounded-xl border border-slate-200 px-3 py-2.5" /><input name="date" required type="date" className="rounded-xl border border-slate-200 px-3 py-2.5" /><input name="time" required type="time" className="rounded-xl border border-slate-200 px-3 py-2.5" /><select name="status" className="rounded-xl border border-slate-200 px-3 py-2.5"><option>Confirmed</option><option>Pending</option><option>Completed</option></select><select name="payment" className="rounded-xl border border-slate-200 px-3 py-2.5"><option>Unpaid</option><option>Deposit</option><option>Paid</option></select><select name="paymentMethod" className="rounded-xl border border-slate-200 px-3 py-2.5 sm:col-span-2"><option>Cash</option><option>Card</option><option>GCash</option><option>Bank transfer</option></select></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancel</button><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-white">Create booking</button></div></form></div>}
  </div>;
}
